[build]
  command = "npm run build || true"
  node_version = "18"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development" 